name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development'
    runs-on:
      group: default
    #runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      #e
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --passWithNoTests

      - name: Run Build
        run: yarn build